# Generated by Django 5.0.4 on 2024-06-24 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoExchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=512, verbose_name="Name"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(max_length=64, verbose_name="Symbol"),
                ),
                (
                    "is_crypto",
                    models.BooleanField(
                        default=False, verbose_name="Is cryptocurrency"
                    ),
                ),
                (
                    "use_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Use count"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created On"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CryptoExchangeSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "display_symbol",
                    models.CharField(
                        max_length=255, verbose_name="Display Symbol"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(max_length=255, verbose_name="Symbol"),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbols",
                        to="symbol.cryptoexchange",
                    ),
                ),
            ],
        ),
    ]
